QuestIntern/Application/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.startup),
    path('signup',views.usignup),
    path('signningup',views.signingup),
    path('loggingin',views.ulogin),
    path('logout',views.ulogout),
    path('addjob',views.add_job),
    path('insertjob',views.insert_job,name="insert_job"),
]

QuestIntern/QuestIntern/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Application.urls'))
]

QuestIntern/Application/models.py
from django.db import models

class Job(models.Model):
    url = models.URLField()
    posted_by = models.CharField(max_length=255)
    company = models.CharField(max_length=255,default="unknown")
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    year_from = models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])

    def __str__(self):
        return f"{self.posted_by} - {self.url}"

QuestIntern/Application/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import send_mail
from .models import Job
import random

def startup(request):
    jobs = Job.objects.all()
    return render(request, 'home.html', {'jobs': jobs})

def usignup(request):
    return render(request,'signup.html')

def signingup(request):
    if request.method =='POST':
        uname = request.POST['user-name']
        upass = request.POST['user-password']
        umail = request.POST['user-email']
        if umail.__contains__('@srmist.edu.in'):
            # Mail
            subject = 'Greetings from Quest Intern'
            otp = random.randint(1000,9999)
            message = 'Welcome '+ uname+' for Logging in QuestIntern \n Your Otp is '+str(otp)
            from_email = settings.EMAIL_HOST_USER 
            to_list = [umail]
            try:
                send_mail(subject,message,from_email,to_list,fail_silently=True)
            except Exception as e :
                print(e)
            myuser = User.objects.create_user(uname,umail,upass)
            myuser.save()
            alert_message='Congragulations!! '+uname+', Your InternQuest Account has been Successfully Created.'
            messages.success(request,alert_message)
            response = redirect('/')
            return response
        else:
            alert_message='Sorry '+uname+', Please login with your SRM email'
            messages.warning(request,alert_message)
            response = redirect('/')
            return response

def ulogin(request):
    if request.method == "POST":
        uname = request.POST['user-name']
        upass = request.POST['user-password']
        user = authenticate(username=uname,password=upass)
        if user is not None:
            login(request,user)
             # Welcome Mail
            subject = 'Greetings from InternQuest'
            msg= 'Hi '+uname+' you are now logged in'
            message = 'Hi '+uname +' A Login Activity Detected For your Account... '
            from_email = settings.EMAIL_HOST_USER 
            to_list = [user.email]  
            send_mail(subject,message,from_email,to_list,fail_silently=True)
            messages.success(request,msg)
            return redirect('/')
        else:
            return HttpResponse('Wrong Password')
    else:
        return HttpResponse("Post Error ")    

def ulogout(request):
    if request.method == "POST":
        logout(request)
        return redirect("/")
    else:
        return HttpResponse('No access')

def add_job(request):
    return render(request,'add_jobs.html')

def insert_job(request):
    if request.method == 'POST':
        url = request.POST['job_url']
        company = request.POST['company']
        salary = request.POST['salary']
        year_from = request.POST['year_from']

        posted_by = request.user.username
        job = Job.objects.create(
            url=url,
            posted_by=posted_by,
            company=company,
            salary=salary,
            year_from=year_from
        )
        return redirect('/')
    else:
        return render(request, 'home.html')
    

QuestIntern/templates/add_jobs.html
<html>
<head>
    <title>Add Job</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
</head>
<body class="flex flex-col min-h-screen">
{% include 'header.html' %}
<div class="flex-grow">
    <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <form method="post" action="{% url 'insert_job' %}" class="flex flex-col text-center w-full mb-12">
            {% csrf_token %}
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Add Job</h1>
            <div class="flex lg:w-2/3 w-full sm:flex-row flex-col mx-auto px-8 sm:space-x-4 sm:space-y-0 space-y-4 sm:px-0 items-end">
                <div class="relative flex-grow w-full">
                    <label for="url" class="leading-7 text-sm text-gray-600">URL</label>
                    <input type="url" id="url" name="job_url" required class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-blue-500 focus:bg-transparent focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                </div><br>
                <div class="relative flex-grow w-full">
                    <label for="company" class="leading-7 text-sm text-gray-600">Company</label>
                    <input type="text" id="company" name="company"  class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-blue-500 focus:bg-transparent focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                </div><br>
                <div class="relative flex-grow w-full">
                    <label for="salary" class="leading-7 text-sm text-gray-600">Salary</label>
                    <input type="number" id="salary" name="salary" required class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-blue-500 focus:bg-transparent focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                </div><br>
                <div class="relative flex-grow w-full">
                    <label for="year_from" class="leading-7 text-sm text-gray-600">Year From</label>
                    <select id="year_from" name="year_from" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-blue-500 focus:bg-transparent focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                        <option value="1">1st Year</option>
                        <option value="2">2nd Year</option>
                        <option value="3">3rd Year</option>
                        <option value="4">4th Year</option>
                    </select>
                </div>
                <input type="submit" value="Add Job" class="text-white bg-blue-500 border-0 py-2 px-8 focus:outline-none hover:bg-blue-600 rounded text-lg">
            </div>
        </form>
    </div>
</section>
</div>

{% include 'footer.html' %}
</body>
</html>

QuestIntern/templates/all_jobs.html
<!-- templates/jobs/all_jobs.html -->

<!DOCTYPE html>
<html>
<head>
    <title>All Jobs</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            // Function to filter jobs based on selected year
            function filterJobs(year) {
                $('ul li').show();  // Show all jobs
                if (year !== 'all') {
                    $('ul li').not(`:contains('${year}')`).hide();  // Hide jobs with the non-selected year
                }
            }

            // Event handler for the filter dropdown change
            $('#year_filter').change(function () {
                var selectedYear = $(this).val();
                filterJobs(selectedYear);
            });
        });
    </script>
</head>

<body>
   <div class="flex justify-end">
    <div class="ml-4">
        <label for="year_filter" >Filter by Year:</label>
        <select id="year_filter" class="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300 dark:bg-gray-700 dark:text-white">
            <option value="all" selected class="hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">All Years</option>
            <option value="1" class="hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">1st Year</option>
            <option value="2" class="hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">2nd Year</option>
            <option value="3" class="hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">3rd Year</option>
            <option value="4" class="hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">4th Year</option>
        </select>
    </div>
</div>


    <ul>
        {% for job in jobs %}
            <li>
                <section class="text-gray-600 body-font overflow-hidden">
                    <div class="container px-5 py-24 mx-auto">
                        <div class="-my-8 divide-y-2 divide-gray-100">
                        <div class="py-8 flex flex-wrap md:flex-nowrap">
                            <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                            <span class="font-semibold title-font text-gray-700">Posted By</span>
                            <span class="mt-1 text-gray-500 text-sm">{{ job.posted_by }}</span>
                            </div>
                            <div class="md:flex-grow">
                            <h2 class="text-2xl font-medium text-gray-900 title-font mb-2">{{ job.company }}</h2>
                            <p class="leading-relaxed">
                                Salary: {{ job.salary }}
                            </p>
                            <p class="leading-relaxed">
                                Eligible above: {{ job.get_year_from_display }}
                            </p>
                            <a href="{{ job.url }}" class="text-indigo-500 inline-flex items-center mt-4">Apply for this job
                                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M5 12h14"></path>
                                <path d="M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                            </div>
                        </div>
                        </div>
                    </div>
                </section>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

QuestIntern/templates/footer.html
    <!-- footer  -->
<footer class="text-gray-400 bg-gray-900 body-font">
        <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
          <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">InternQuest</span>
          </a>
          <p class="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-800 sm:py-2 sm:mt-0 mt-4">© 2024 InternQuest —
            <a href="#" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">@Vertexx</a>
          </p>
          </span>
        </div>
</footer>
     

QuestIntern/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <header class="text-gray-400 bg-gray-900 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
              <a href = '/' 
             <span class="ml-3 text-xl">InternQuest</span>
          </a> 
          <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
          </nav>
          {% if user.is_authenticated %}
          <form action="addjob" method="post">{% csrf_token %}
            <button class="block text-white bg-blue-300 hover:bg-blue-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"  type="submit">POST_JOBS</button>
          </form>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <form action="logout" method="post">{% csrf_token %}
              <button class="block text-white bg-red-500 hover:bg-red-400 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" type="submit">Logout</button>

          </form>
          {% else %}
          <button class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button" data-modal-toggle="authentication-modal">
            Login
          </button>
          {% endif %}
            <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
        </div>
      </header>   

<!-- Main modal -->
<form action='loggingin' method="post">{% csrf_token %}  
  <div id="authentication-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
  <div class="relative w-full h-full max-w-md md:h-auto">
      <!-- Modal content -->
      <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-toggle="authentication-modal">
              <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
              <span class="sr-only">Close modal</span>
          </button>
          <div class="px-6 py-6 lg:px-8">
              <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Sign in to our platform</h3>
              <form class="space-y-6" action="#">
                  <div>
                      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                      <input type="text" name="user-name" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="name@company.com" required>
                  </div>
                  <div>
                      <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
                      <input type="password" name="user-password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                  </div>
                  <br>
                  <button type="submit"  class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login to your account</button>
                  <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                      Not registered? <a href="signup" class="text-blue-700 hover:underline dark:text-blue-500">Create account</a>
                  </div>
              </form>
          </div>
      </div>
  </div>
  </div> 
</form>
<script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"></script>


</body>
</html>

QuestIntern/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
    <title>Document</title>
</head>
<body class="flex flex-col min-h-screen">

    {% include 'header.html' %}

    <div class="flex-grow overflow-y-auto">
        {% for message in messages %}
        <div class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
            <strong>Message : </strong> {{ message }}
        </div>
        {% endfor %}

        {% include 'all_jobs.html' %}
    </div>

    {% include 'footer.html' %}

</body>

</html>

QuestIntern/templates/otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
    <title>OtpVerification</title>
</head>
<body>
    <div class="h-screen bg-blue-500 py-20 px-3">
        <div class="container mx-auto">
            <div class="max-w-sm mx-auto md:max-w-lg">
                <div class="w-full">
                    <div class="bg-white h-64 py-3 rounded text-center">
                          <h1 class="text-2xl font-bold">OTP Verification</h1>
                          <div class="flex flex-col mt-4">
                              <span>Enter the OTP you received at</span>
                              <span class="font-bold">+91 ******876</span>
                          </div>
                          
                          <div id="otp" class="flex flex-row justify-center text-center px-2 mt-5">
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="first" maxlength="1" /> 
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="second" maxlength="1" /> 
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="third" maxlength="1" /> 
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="fourth" maxlength="1" />
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="fifth" maxlength="1" /> 
                <input class="m-2 border h-10 w-10 text-center form-control rounded" type="text" id="sixth" maxlength="1" />
                          </div>
                          
                          <div class="flex justify-center text-center mt-5">
                              <a class="flex items-center text-blue-700 hover:text-blue-900 cursor-pointer"><span class="font-bold">Resend OTP</span><i class='bx bx-caret-right ml-1'></i></a>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

QuestIntern/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Signup</title>
</head>
<body>
  {% include 'header.html' %}


<form action="signningup" method="post">{% csrf_token %}
  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
      <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
        <h1 class="title-font font-medium text-3xl text-gray-900">Your Quest for Professional Growth </h1>
          <p class="leading-relaxed mt-4">Bridge the gap between education and industry with InternQuest </p>
      </div>
      <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
            <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign Up</h2>
      <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">Full Name</label>
        <input type="text" id="full-name" name="user-name" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
        <input type="emaul" id="email" name="user-email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="email" class="leading-7 text-sm text-gray-600">Create Password</label>
        <input type="password" id="email" name="user-password" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <button class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Signup</button>
      
      </div>
    </div>
  </section>
  
</form>
    


{% include 'footer.html' %}  
<script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"></script>
</body>
</html>